### ISSUE TITLE
按reload之後crash了

### ISSUE THREAD

**Issue by BrianOn99** [BrianOn99/CU-loopbook#1]
幾日無開過個app，再開時Android無重新啟動個app（因為無顯示"connecting" toast)。之後按reload就crash了。logcat如下：

```
E/AndroidRuntime(  501): FATAL EXCEPTION: main
E/AndroidRuntime(  501): java.lang.NullPointerException
E/AndroidRuntime(  501):    at com.loopbook.cuhk_loopbook.BookFragment.refresh(BookFragment.java:38)
E/AndroidRuntime(  501):    at com.loopbook.cuhk_loopbook.MainActivity.onOptionsItemSelected(MainActivity.java:110)
E/AndroidRuntime(  501):    at android.app.Activity.onMenuItemSelected(Activity.java:2202)
E/AndroidRuntime(  501):    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
E/AndroidRuntime(  501):    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
E/AndroidRuntime(  501):    at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
E/AndroidRuntime(  501):    at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
E/AndroidRuntime(  501):    at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:74)
E/AndroidRuntime(  501):    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
E/AndroidRuntime(  501):    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:740)
E/AndroidRuntime(  501):    at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
E/AndroidRuntime(  501):    at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
E/AndroidRuntime(  501):    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
E/AndroidRuntime(  501):    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
E/AndroidRuntime(  501):    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
E/AndroidRuntime(  501):    at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
E/AndroidRuntime(  501):    at android.view.View.performClick(View.java:2408)
E/AndroidRuntime(  501):    at android.view.View$PerformClick.run(View.java:8817)
E/AndroidRuntime(  501):    at android.os.Handler.handleCallback(Handler.java:587)
E/AndroidRuntime(  501):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime(  501):    at android.os.Looper.loop(Looper.java:144)
E/AndroidRuntime(  501):    at android.app.ActivityThread.main(ActivityThread.java:4937)
E/AndroidRuntime(  501):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(  501):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime(  501):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
E/AndroidRuntime(  501):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
E/AndroidRuntime(  501):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(   95):   Force finishing activity com.loopbook.cuhk_loopbook.multilang/com.loopbook.cuhk_loopbook.MainActivity
W/ActivityManager(   95): Activity pause timeout for HistoryRecord{46275208 com.loopbook.cuhk_loopbook.multilang/com.loopbook.cuhk_loopbook.MainActivity}
I/ActivityManager(   95): Process com.loopbook.cuhk_loopbook.multilang (pid 501) has died.
```

**Comment by Energy0124** [comment]
Seems to me that for some reasons `data` is not initialized, or the reference to the original `data` is lost, but I am not familiar with android development.

**Comment by BrianOn99** [comment]
I also wonder why the reference is lost.  Thank you.

**Comment by BrianOn99** [comment]
I have figured out one possibility.
According to [android activity lifecycle](http://stackoverflow.com/questions/6812003/difference-between-oncreate-and-onstart), the [onCreate method of the MainActivity](https://github.com/BrianOn99/CU-loopbook/blob/43d53701f1b892171055541dab399a9f739a160c/app/src/main/java/com/loopbook/cuhk_loopbook/MainActivity.java) may be called when it is first created or reload after killed.  The bug happens in the latter case.  On line 33 of onCreate, a new bookfragment is created, so the original reference is lost.  However, the new bookfragment is not used (line 49)
