### ISSUE TITLE
Refresh and BookAdapter race condition

### ISSUE THREAD

**Issue by BrianOn99** [BrianOn99/CU-loopbook#2]
It is VERY rare, but serious:
open app with some books -> settings -> change to account with no books -> back to main screen -> crash (with low probability)

```
E/AndroidRuntime( 3119): FATAL EXCEPTION: main
E/AndroidRuntime( 3119): java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
E/AndroidRuntime( 3119):    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:257)
E/AndroidRuntime( 3119):    at java.util.ArrayList.get(ArrayList.java:311)
E/AndroidRuntime( 3119):    at com.loopbook.cuhk_loopbook.BookFragment$BookAdapter.getView(BookFragment.java:74)
E/AndroidRuntime( 3119):    at android.widget.AbsListView.obtainView(AbsListView.java:1315)
E/AndroidRuntime( 3119):    at android.widget.ListView.measureHeightOfChildren(ListView.java:1198)
```

**Comment by BrianOn99** [comment]
I think it is because when the ListView is rerendered, the old books still exist, and getCount() (from BookAdapter) give some non-zero number to Android.
However, before the listview is fully rendered, the books are cleared by AsyncBookLoader (how rare it is!)
